status: successfull # successfull error or warning
message: >
- date: December 1, 2015
  time: "08:00 GMT+0"
  We currently have a problem with the Mail services in the server.
  This causes monthly reports to be sent multiple times.
  We are sorry for the inconvinience with this and are working to restore the problem.
  (It is possible to turn the reports off, this is done in the "Cluster Preferences".)
  state: Mail Service problems
  All systems operational. <br />
